### ISSUE TITLE
content of transformed iframe is visible outside of the iframe

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#11358]
follow up of https://github.com/servo/servo/issues/11151

```html
<style>
  body {
    background: green;
  }
  iframe  {
    width: 100vw;
    height: 100vh;
    border: 10px solid red;
    transform: scale(.5);
  }
</style>
<iframe src="data:text/html,<body style='overflow: hidden; overflow-y: auto;'><div style='background: blue; height: 2000px'>"></iframe>
```

<img width="531" alt="screen shot 2016-05-24 at 09 20 46" src="https://cloud.githubusercontent.com/assets/373579/15495527/d4d3dd76-2190-11e6-9ead-a47c380b514f.png">

**Comment by nox** [comment]
Interesting, on latest master on my computer it is less visible, just covering the border:
![capture d ecran 2016-05-24 a 14 20 42](https://cloud.githubusercontent.com/assets/123095/15503546/b601dd56-21ba-11e6-8448-dee45dc77a3c.png)

**Comment by paulrouget** [comment]
@nox I can't reproduce that. Can you still reproduce after the latest webrender updates?

**Comment by paulrouget** [comment]
@nox You probably didn't use webrender.

**Comment by nox** [comment]
Indeed I didn't use webrender. Can reproduce now.

**Comment by nox** [comment]
#11398

**Comment by metajack** [comment]
Pretty sure @pcwalton is on this.

**Comment by pcwalton** [comment]
Yup, this was on my agenda for today.

**Comment by pcwalton** [comment]
Reopening since we need a wrup.

**Comment by pcwalton** [comment]
Fixed by #11398.

**Comment by Gozala** [comment]
#11398 seems to fix specific example @paulrouget posted, but issue still remains if different css transforms are used. In browser.html we use `translate3d` that still seems to have this issue. I have update original code example to illustrate the issue:

```html
<style>
  body {
    background: green;
    perspective: 1000px;
    height: 100vh;
    width: 100vw;
  }
  
  iframe {
    width: 100%;
    height: 100%;
    border: 10px solid red;
    transform: translate3d(0px, 0px, -800px);
  }
</style>
<iframe src="data:text/html,<body style='overflow: hidden; overflow-y: auto;'><div style='background: blue; height: 2000px'>"></iframe>
```

I also published it to jsbin so it's easy to reproduce:

```
servo -w https://jsbin.com/cupoza
```

P.S. If you scroll iframe content it will escape top boundary as well.

**Comment by Gozala** [comment]
Never mind, it looks like we already have a bug #11650 on file the issue I posted above
