### ISSUE TITLE
The computed `font-size` and `line-height` must be clamped when the specified value is out-of-range

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15296]
Although it is invalid to specify something like `font-size: -1px`, it is allowed to do `font-size: calc(-1px)`. In the latter case, `font-size` must be computed to zero rather than `-1px`.

The spec: https://drafts.csswg.org/css-values-3/#calc-range

The relevant code is probably https://github.com/servo/servo/blob/master/components/style/properties/longhand/font.mako.rs#L378-L382

(I found `font-size` and `line-height`, but other properties may be affected as well.)

**Comment by Maaarcocr** [comment]
What I'm going to say may be really wrong, due to my ignorance about how style works in servo. 

Wouldn't it be better if every property that can implement calc() should provide a maximum and minimum value for calc()?

**Comment by Manishearth** [comment]
We should add a `to_computed_value_positive` method that takes the result of `to_computed_value()` and clamps it.

**Comment by upsuper** [comment]
That should be `to_computed_value_non_negative`. I actually think we should somehow put non-negative into the type system, so that we can enforce it everywhere. Many properties would need this.

**Comment by nox** [comment]
I am pretty sure I fixed this in https://github.com/servo/servo/pull/16382.

**Comment by upsuper** [comment]
Actually it isn't fixed. The issue can still be reproduced with
```html
<div id="test"></div>
<script>
test.style.fontSize = 'calc(-1px)';
alert(getComputedStyle(test).fontSize);
</script>
```

**Comment by nox** [comment]
https://github.com/servo/servo/blob/9a419ec3d50436b3a91227880114d9985f2097e7/components/style/properties/longhand/font.mako.rs#L801-L805

**Comment by nox** [comment]
I'm not sure `to_computed_value_non_negative` would make a lot of sense on `CalcLengthOrPercentage`, we can't know for sure whether `30px - 10%` is negative or not. `font-size` is a special snowflake though.

**Comment by nox** [comment]
Actually am wrong, but there should still not be any `to_computed_value_non_negative` method, instead `calc()` values should remember that they should clamp themselves when needed.
