### ISSUE TITLE
text rendering looks terrible at low point sizes

### ISSUE THREAD

**Issue by imiuka** [servo/servo#17190]
hey there,

on windows 10, servo's text rendering looks really bad, especially compared how chrome, edge and firefox the same slab of text. i'm using the latest nightly build (published on 2017-06-05).

the spacing between glyphs looks off, but ignoring that, the glyphs themselves look "wrong" - blurry and fat.

here is one screenshot that shows how it appears (to my untrained eye) to affect mostly small point sizes:
![servo example](https://user-images.githubusercontent.com/975570/26844210-056f0b8e-4b36-11e7-9127-91aa060a508e.png)

this affects real world pages, too:
![wikipedia example](https://user-images.githubusercontent.com/975570/26844222-12c6c3b2-4b36-11e7-890a-5d5fb49c9ebc.png)

![servo home example](https://user-images.githubusercontent.com/975570/26844332-647aeb98-4b36-11e7-8f68-6304b7f678e0.png)

the page used in the first example is available online at http://a.unyaa.com/2017/wr-644cb.html, which you can type into servo and another browser to compare yourself.

**Comment by atouchet** [comment]
This has been bothering me as well. I believe this is a somewhat recent change too. For reference here is a screenshot of the Servo Windows build from March 13:

![Windows UI](https://i.imgur.com/xovvdOq.png "Windows UI")

**Comment by imiuka** [comment]
servo was still ok on 2017-04-12 (equivalent to your 2017-03-13 screenshot). haven't had the time to do a dissect on changes between then and now.

unsure if this should be filed in a separate issue(?), but even when the change is reverted, servo's glyph rendering still looks crappy compared with all other browsers. i think this is partially servo layouting, and partially webrender rendering.

- [servo 2017-06-05 (affected)][1]
- [servo 2017-04-13 (unaffected, looks better, but low quality compared to below)][2]
- [chrome 2017-06-08 (reference)][3]
- [edge 2017-06-08 (reference)][4]
- [firefox 2017-06-08 (reference)][5]

[1]: http://a.unyaa.com/2017/servo-dafc3b2470327b6357a6e4ee03cc9a9f/servo-2017-06-05.png
[2]: http://a.unyaa.com/2017/servo-dafc3b2470327b6357a6e4ee03cc9a9f/servo-2017-04-13.png
[3]: http://a.unyaa.com/2017/servo-dafc3b2470327b6357a6e4ee03cc9a9f/chrome-2017-06-08.png
[4]: http://a.unyaa.com/2017/servo-dafc3b2470327b6357a6e4ee03cc9a9f/edge-2017-06-08.png
[5]: http://a.unyaa.com/2017/servo-dafc3b2470327b6357a6e4ee03cc9a9f/firefox-2017-06-08.png

**Comment by atouchet** [comment]
This issue appears to be noticeably improved in the latest nightly build.

**Comment by hinaria** [comment]
I'm not sure if it has - take a look at the example below (taken from today's nightly build, 2017-07-30).

![example](https://user-images.githubusercontent.com/975570/28762562-e839d388-75fa-11e7-945c-50c170af8779.png)

We fixed the incorrect line height issue in #17340 last month, but the glyph layout and rendering does not feel like it's changed for me.

**Comment by atouchet** [comment]
It's still not great for sure but I do see a really noticeable difference on some sites. For example the Browser.html homescreen.

Here's a screencap from today's build:

![Browser.html homescreen](https://i.imgur.com/SLbroF9.png)

That looks much better to me than the example in your original post.

**Comment by hinaria** [comment]
You're right, I stand corrected! Thank you.

There are still some issues with sub-pixel + aa, but it should not be too much work to make layout better.

I'll also experiment with a DirectWrite implementation for layout - I've been using it with WebRender in one of my projects and have had great results with it.

**Comment by atouchet** [comment]
The kerning issues appear to be largely fixed with #18567.

**Comment by atouchet** [comment]
The Browser.html homescreen font rendering appears to be getting thicker again.

![Servo](https://i.imgur.com/nRvZhel.png)

**Comment by atouchet** [comment]
The latest WebRender updates appear to have largely fixed the Windows text rendering issues. Screenshots from the latest nightly build:

![Servo](https://i.imgur.com/gxBh3k4.png)

![Servo](https://i.imgur.com/VuDeVTI.png)

![Servo](https://i.imgur.com/byLm4TM.png)

@hinaria what do you think? Should this issue be closed now?

**Comment by glennw** [comment]
@atouchet Thanks for following up on this!

**Comment by atouchet** [comment]
@glennw I've been taking a closer look at the Windows text rendering and I think there are still a few issues (and maybe a regression since my last post). However I'm not sure which of these are deliberate behaviours or not. Let me know if it would be better to open a WebRender issue report for any/all of these.

Here are a few comparison images from DuckDuckGo, GitHub, and Hacker News. The top versions are Servo and the bottom versions are Firefox (without WebRender).

![DuckDuckGo](https://i.imgur.com/uRESbZD.png)

![GitHub](https://i.imgur.com/tVNFn8D.png)

![Hacker News](https://i.imgur.com/m8Slvt6.png)

The DuckDuckGo examples are fairly close but the Servo version looks slightly darker and there is more vertical spacing between lines (this might just be another Servo problem). In the GitHub examples the Servo text looks noticeably blurrier than the Firefox text. In the Hacker News examples the Servo text appears thicker than the Firefox text and wider too. The smaller text look like they aren't even the same font sizes, I'm not sure what's going on there.

Some specific issues I've noticed:

1. Text pixel colour is now uniform where it used to be somewhat variable. This has changed since my last post where Servo did not used to behave this way. For example here is a zoomed image of Sandra Bullock's Wikipedia page. The top paragraph is from the latest Servo nightly build and the bottom paragraph is from my previous post from November.

![Wikipedia](https://i.imgur.com/NheuEBg.png)

The black text is now completely monochrome and it did not used to be (it is easier to see this when clicking on the image to load it full size). Is this intentional or a regression? I believe this may be the cause of text appearing darker or thicker in Servo as this appears to impact multiple sites.

![Hacker News](https://i.imgur.com/OgS8bg8.png)

When the Hacker News text is viewed zoomed in it's clear that the text isn't any thicker but that the grey instead of the lighter colours make it look that way.

2. Some text exhibits blurry or inconsistent glyph rendering. For example on GitHub:

![GitHub](https://i.imgur.com/vpcT6hG.png)

The quotation marks and certain letters (like the H in "GitHub") appear much less defined in Servo. There are also noticeable inconsistencies between different examples of the same letters. In the Servo example the "p"s in "privacy policy" do not look the same at all, the second one is much blurrier. In the Firefox example the letters look identical.

3. Spacing and size issues. I don't know if this is due to the text rendering or not but as seen in the DuckDuckGo and Hacker News examples there are some issues where the spacing and size of text in Servo does not match that of Firefox.

**Comment by glennw** [comment]
@atouchet Thanks for writing this up! I'll also CC @Gankro who works on text + WR + gecko - he may have some comments / thoughts on this too.

**Comment by Gankro** [comment]
It just looks like servo's bindings to webrender are messed up, and it has disabled subpixel-aa on all of it's text. No clue where (just woke up and downloaded the nightly build).

This isn't an issue that affects gecko.

**Comment by atouchet** [comment]
I bisected the text colour issue and the first nightly build with the problem is 2017-11-23.

**Comment by atouchet** [comment]
The text colour issue has been fixed but the other problems still occur in the latest nightly build.

**Comment by webbedspace** [comment]
I did a quick comparison using this:
```html
<!doctype html><body style="font-family:sans-serif;font-size:10px;background:white">privacy policy</body>
```

Top to bottom: Servo, Chrome, Firefox
<img width="823" height="530" alt="Image" src="https://github.com/user-attachments/assets/be4b9f78-b3d2-41c1-b4f6-0132b7c900fe" />

So the subpixel rendering is a bit different for specifically this case.
