### ISSUE TITLE
three.js css3d sandbox example renders incorrectly

### ISSUE THREAD

**Issue by jdm** [servo/servo#21001]
https://threejs.org/examples/css3d_sandbox.html

**Comment by nox** [comment]
This actually has no WebGL involved, just CSS.

**Comment by lumiscosity** [comment]
The only thing that seems to be off is that the fully transparent bits are a tad blurry. Unfortunately, it's hard to compare this one due to its random nature and the fact that it routinely crashes on refresh (as do many of these):

```
assertion `left == right` failed
  left: 5425430176097894400
 right: 0 (thread Script#1, at /home/maple/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mozjs_sys-140.10.1-0/src/jsval.rs:505)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::panic_with_hook
   3: std::panicking::panic_handler::{closure#0}
   4: std::sys::backtrace::__rust_end_short_backtrace::<std::panicking::panic_handler::{closure#0}, !>
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::assert_failed_inner
   8: core::panicking::assert_failed::<u64, u64>
   9: <script::dom::abortsignal::AbortSignal as script_bindings::weakref::WeakReferenceable>::downgrade
  10: <script::dom::webgl::webglobject::WebGLObject>::new_inherited
  11: <script::dom::webgl::webgltexture::WebGLTexture>::new_inherited
  12: <script::dom::webgl::webglrenderingcontext::WebGLRenderingContext as script_bindings::codegen::GenericBindings::WebGLRenderingContextBinding::WebGLRenderingContext_Binding::WebGLRenderingContextMethods<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder>>::CreateTexture
  13: script_bindings::codegen::GenericBindings::WebGL2RenderingContextBinding::WebGL2RenderingContext_Binding::createTexture::<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder>::{closure#0}
  14: mozjs::panic::wrap_panic
  15: script_bindings::codegen::GenericBindings::WebGL2RenderingContextBinding::WebGL2RenderingContext_Binding::createTexture::<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder>
  16: CallJitMethodOp
  17: script_bindings::utils::generic_call::<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder, false>
  18: script_bindings::utils::generic_method::<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder, script_bindings::utils::call_policies::CrossOriginCallable, false>
  19: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  20: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  21: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  22: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  23: _ZL17InternalConstructP9JSContextRKN2js16AnyConstructArgsENS1_10CallReasonE
  24: _ZN2js3jit14DoCallFallbackEP9JSContextPNS0_13BaselineFrameEPNS0_14ICFallbackStubEjPN2JS5ValueENS7_13MutableHandleIS8_EE
  25: <unknown>
```
(Note that this is a production build, so the logs might not be as helpful.)

Tested on Arch Linux x86_64, Servo built against commit 0df60d7cebc5f335fd0096702659b0e9c39d86e0, compared against Firefox 151.0.3.

<img width="1762" height="1000" alt="Image" src="https://github.com/user-attachments/assets/e2ac7c15-8268-44a7-ba4e-c53b7b700c10" />

**Comment by jdm** [comment]
Those crashes are fixed on main by https://github.com/servo/servo/pull/45515.

**Comment by lumiscosity** [comment]
> Those crashes are fixed on main by [#45515](https://github.com/servo/servo/pull/45515).

I have that commit on my branch already and it still happens. I even tried updating again, running ./mach clean and rebuilding.

**Comment by jdm** [comment]
Huh, I can't reproduce that even when spamming the refresh keybinding.

**Comment by lumiscosity** [comment]
...nevermind. I was on another branch and didn't realize, sorry.

**Comment by jdm** [comment]
Let's call this one done.
