### ISSUE TITLE
Google.com is laid out incorrectly

### ISSUE THREAD

**Issue by dralley** [servo/servo#26096]
![Screenshot from 2020-04-02 12-01-50](https://user-images.githubusercontent.com/2751996/78271324-0263aa00-74da-11ea-9a1c-c0d489d45a3c.png)

**Comment by dralley** [comment]
Seems like it's fixed now.

**Comment by atouchet** [comment]
I still see the issue using the latest nightly build.

![Screenshot](https://i.imgur.com/jA3KGDh.png)

**Comment by dralley** [comment]
Interesting, in the US they have a themed logo today, and it works.  But I tried it again recently on days when it had the "normal" logo like this, and it was still broken.  So maybe it can be narrowed down to a difference in the pages.

**Comment by arihant2math** [comment]
I'm not seeing any icons at all oddly:

![Image](https://github.com/user-attachments/assets/d838992d-cec3-4863-a9df-0e2a4946a755)

**Comment by jdm** [comment]
The icons and logo are all SVG at the moment, and Servo doesn't support SVG yet. #36721 won't affect this, since the logo is inline SVG content in the document.

**Comment by arihant2math** [comment]
Interesting. What's the difference between non-inline and inline svgs from a handling perspective?

**Comment by arihant2math** [comment]
Pretty much fixed 🎉 . But there are a few issues:

- AI Mode is offcenter of it's button
- the footer is swapped (the applying AI towards since and the environment is supposed to be in the center, not off on the left side).

Servo:
<img width="3243" height="1448" alt="Image" src="https://github.com/user-attachments/assets/8aec16ac-542d-4331-b63b-487228ab9364" />

**Comment by simonwuelker** [comment]
The issue with the AI mode button is tracked in https://github.com/servo/servo/issues/36944. We don't support button layout at all I think.
