### ISSUE TITLE
Crash On Startup Windows 10

### ISSUE THREAD

**Issue by NobodyWithNoName** [servo/servo#28622]
Hi, I just downloaded servo for windows (zip) from https://servo.org and run it, a blank window appears and closes in less than 1 seconds, what is wrong?

**Comment by jdm** [comment]
The best way to answer that question is to build it from source and see what output appears. I'm not sure that any current Servo developers have access to a Windows environment.

**Comment by shiyou0130011** [comment]
I have the same issue. 

I download servo (Windows exe) today. sha256 is `ced375279e21eab28166849b4ab01228cb9a5335d3da162128d4baa63f4f6fac`

The error log is 

```
assertion failed: !handle.is_null() (thread main, at /rustc/e249ce6b2345587d6e11052779c86adbad626dff\library\std\src\os\windows\io\handle.rs:183)
```

**Comment by jdm** [comment]
Can you run with RUST_BACKTRACE=1? That should provide more useful output.

**Comment by shiyou0130011** [comment]
> Can you run with RUST_BACKTRACE=1? That should provide more useful output.

No, but the error log has more information now:

```
assertion failed: !handle.is_null() (thread main, at /rustc/e249ce6b2345587d6e11052779c86adbad626dff\library\std\src\os\windows\io\handle.rs:183)
   0: moz_dispose_arena
   1: moz_dispose_arena
   2: mozilla::detail::ConditionVariableImpl::notify_all
   3: moz_create_arena_with_params
   4: moz_dispose_arena
   5: moz_create_arena_with_params
   6: mozilla::detail::ConditionVariableImpl::notify_all
   7: mozilla::detail::ConditionVariableImpl::notify_all
   8: mozilla::detail::ConditionVariableImpl::notify_all
   9: mozilla::detail::ConditionVariableImpl::notify_all
  10: mozilla::ProcessUptimeExcludingSuspendMs
  11: mozilla::ProcessUptimeExcludingSuspendMs
  12: HeapFree
  13: HeapFree
  14: mozilla::detail::ConditionVariableImpl::notify_all
  15: mozilla::detail::ConditionVariableImpl::notify_all
  16: mozilla::detail::ConditionVariableImpl::notify_all
  17: moz_create_arena_with_params
  18: moz_create_arena_with_params
  19: moz_create_arena_with_params
  20: moz_create_arena_with_params
  21: moz_dispose_arena
  22: moz_create_arena_with_params
  23: moz_create_arena_with_params
  24: moz_dispose_arena
  25: moz_create_arena_with_params
  26: moz_create_arena_with_params
  27: moz_create_arena_with_params
  28: moz_create_arena_with_params
  29: moz_create_arena_with_params
  30: moz_create_arena_with_params
  31: mozilla::detail::ConditionVariableImpl::notify_all
  32: moz_create_arena_with_params
  33: mozilla::ProcessUptimeExcludingSuspendMs
  34: BaseThreadInitThunk
  35: RtlUserThreadStart
```

**Comment by jdm** [comment]
Ok, it looks like we might be able to address this by updating to a newer nightly of Rust that includes https://github.com/rust-lang/rust/commit/3b974813871a4dee6cac3128a4e3fa5e81125464.

**Comment by NobodyWithNoName** [comment]
Is it fixed now?

**Comment by jdm** [comment]
Run a nightly build and find out? I don't have access to a Windows environment.

**Comment by Jon-guy30** [comment]
Still not working. I was interested in running servo on Windows, it's not even starting. The hashes on the website also doesn't match.
`99b0de8c98b971cad6556fee493e324b7e484608b8ac707dafc25b634d9e6af1` Hash for Windows EXE `841adfcaa2171263710cf7b85f0e85ceb6e0e90b9059a1c58983399f3e1539d7` Hash for the ZIP download.

Correct hash according to the post above `99f8c740d80885d15885aa4280930ec747b15d4097d90e67101f7dbda82b01d8`. 

Have the Windows Nightlies EXE and ZIP downloads on the Servo website been updated?
