### ISSUE TITLE
Web font requests are missing many settings

### ISSUE THREAD

**Issue by jdm** [servo/servo#36590]
Code: https://github.com/servo/servo/blob/5e2d42e94459af76c8752fef934a7dde8ac5b41a/components/fonts/font_context.rs#L795-L798

Specification:
* https://www.w3.org/TR/css-fonts-4/#font-fetching-requirements
* https://www.w3.org/TR/css-fonts-4/#sp213

RemoteFontDownloader::download needs to have the following information available, which is all obtained from the document:
* the policy container
* the document URL (used for the referrer)
* has trustworthy ancestor origin
* insecure requests policy

We should create a struct containing these in components/fonts/font_context.rs, and add it as an argument to `FontContextWebFontMethods::add_all_web_fonts_from_stylesheet`, `FontContextWebFontMethods::load_web_font_for_script`, and `FontContext::start_loading_one_web_font`, and make it a member of `WebFontDownloadState`. Then we can set the fields of the RequestBuilder appropriately using the values in the new struct, as well as the constant values in the "Font fetching requirements" from the specification.

This should affect the test results in `./mach test-wpt tests/wpt/tests/referrer-policy/css-integration/font-face` and `./mach test-wpt tests/wpt/tests/content-security-policy/font-src`, so the results will need to be [updated](https://book.servo.org/hacking/testing.html#updating-web-platform-test-expectations).

**Comment by uthmaniv** [comment]
Assign this to me please, thanks

**Comment by jdm** [comment]
Done!

**Comment by uthmaniv** [comment]
Hello Jdm , been working on this for some time now and I still can't get a way around `load_all_web_fonts_from_stylesheet_with_guard`'s call to `add_all_web_fonts_from_stylesheet` in components/layout/layout_impl.rs, because `add_all_web_fonts_from_stylesheet` now has a WebFontDocumentContext as a parameter. I tried making use of a new function I created in the ScriptThread which tries getting the global scope provided a pipeline_id, in order to use the global scope methods to create a WebFontContextDocument for the call to add_all_web_fonts_from_stylesheet. How can I get around this please

**Comment by jdm** [comment]
Can you push your changes to a branch so I can see them?

**Comment by uthmaniv** [comment]
> Can you push your changes to a branch so I can see them?

okay , sure.

**Comment by uthmaniv** [comment]
> Can you push your changes to a branch so I can see them?

https://github.com/servo/servo/pull/36707

**Comment by jdm** [comment]
Unfortunately I think what we need is for the code in components/script to prepare the new context struct and pass it into the layout code that can call load_all_web_fonts_from_stylesheet_with_guard. That means it needs to be part of the ReflowRequest struct, and an argument to load_web_fonts_from_stylesheet and add_stylesheet.
