### ISSUE TITLE
panic: called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" } (thread ImageCache#0, at components/shared/compositing/lib.rs:294)

### ISSUE THREAD

**Issue by tharkum** [servo/servo#37161]
**Describe the bug:**
Panic on manual multiple test execution.
Continuous growing open files count (+240 open fds) on [canvas-display-p3-drawImage.https.html](https://github.com/servo/servo/blob/main/tests/wpt/tests/html/canvas/element/manual/wide-gamut-canvas/canvas-display-p3-drawImage.https.html) rerunning and later CRASH.

On each run it creates 240 new Image() -> 240 new images in ImageCache.

```
for (let [filename, expectedPixels] of Object.entries({...imageTests, ...svgImageTests})) {
    for (let contextColorSpace of ["srgb", "display-p3"]) {
        for (let imageDataColorSpace of ["srgb", "display-p3"]) {
            for (let scaleImage of [false, true]) {
```

```
ps -aef | grep servo -> SERVO_PID
sudo ls -l /proc/SERVO_PID/fd | wc -l 
```

**To Reproduce:**
1. Run from console ./mach test-wpt tests/wpt/tests/html/canvas/element/manual/wide-gamut-canvas/canvas-display-p3-drawImage.https.html -r
2. Push "Rerun" button multiple times (~10-15+)
3. Enjoy

Report 1.
```
pid:624043 index out of bounds: the len is 0 but the index is 0 (thread <unnamed>, at /home/huawei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ipc-channel-0.19.0/src/ipc.rs:562)
 0:14.59 pid:624043 called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Uncategorized, message: "Too many open files" } (thread ImageCache#2, at components/shared/compositing/lib.rs:294)
```

Report 2.
`pid:640645 assertion failed: address != MAP_FAILED (thread ImageCache#0, at /home/huawei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ipc-channel-0.19.0/src/platform/unix/mod.rs:771)`

Report 3.
```
pid:641428 index out of bounds: the len is 0 but the index is 0 (thread <unnamed>, at /home/huawei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ipc-channel-0.19.0/src/ipc.rs:562)
 0:14.00 pid:641428 assertion failed: fd >= 0 (thread ImageCache#1, at /home/huawei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ipc-channel-0.19.0/src/platform/unix/mod.rs:1089)
```

**Platform:**
Ubuntu 22.04

**Comment by mrobinson** [comment]
Likely related: #23905 and #34918. Essentially IPC routes and channels open a file descriptor and it is easy to exhaust them if we open channel or create routes per-DOM object.

**Comment by gterzian** [comment]
Besides the above mentioned issue, which are not yet addressable at this stage of design, it would we worth looking into making the below operation non-blocking(which also would save an fd, although probably not the source of the crash, because I assume ipc channels are created elsewhere one a one per image basis and this is just the last creation that triggers a crash):

https://github.com/servo/servo/blob/45072ae2e05c814cde5ea4dcb7f5c73896de86aa/components/shared/compositing/lib.rs#L293

I think this could be done by passing along a `WebViewId`, and have the compositor reply with an image key sent to the script-thread(I guess [via the constellation](https://github.com/servo/servo/blob/45072ae2e05c814cde5ea4dcb7f5c73896de86aa/components/compositing/compositor.rs#L102)?), which would then pass it on to the image cache. This assumes one image cache per script-thread, and one webview per script-thread, which has to be checked. 

This would also address one part of https://github.com/servo/servo/issues/37086(although the actual IPC should still be moved out of the critical section, but at least it wouldn't be always doing a blocking `recv` inside the critical section).

Other methods of the `CrossProcessCompositorApi` doing a `receiver.recv()` could benefit from a similar setup.

**Comment by arihant2math** [comment]
Additionally `ulimit -n 2048` is a quick fix for any individual machine.

**Comment by gterzian** [comment]
Seems to have been fixed by https://github.com/servo/servo/pull/37369; at least I am not getting a crash on mac. Please confirm @tharkum

**Comment by tharkum** [comment]
@gterzian < Sorry for long reply.

I tested on the current version (July 9th) and Servo is still crashed but with another error (?)
after I reached 4000+ opened fds (around 13 test rerun steps).
```
sudo ls -l /proc/2642568/fd | wc -l 
407 (start point)
......
sudo ls -l /proc/2642568/fd | wc -l 
4020 (last point before crash)
```

Crash log:
```
 1:33.01 pid:2642568 assertion failed: fd >= 0 (thread Script(1,1), at /home/huawei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ipc-channel-0.20.0/src/platform/unix/mod.rs:1121)
 1:33.01 pid:2642568    0: <unknown>
 1:33.02 pid:2642568   22: <unknown>
 1:33.02 pid:2642568 called `Result::unwrap()` on an `Err` value: Custom("Cannot consume shared memory region at index 0, there are only 0 regions available") (thread router-proxy, at components/script/script_thread.rs:903)
 1:33.02 pid:2642568    0: <unknown>
 1:33.02 pid:2642568    6: <unknown>
 1:33.09 pid:2642568 
 1:33.09 INFO Pausing until the browser exits
```

**Comment by gterzian** [comment]
Thanks for the update. So it looks like the previous issue was indeed solved, but now the problem is running out of memory to share.

**Comment by tharkum** [comment]
Looks like the following [issue](https://github.com/servo/servo/issues/40344) is related to this as well (`Rerun` button ~ `location.reload()`)

**Comment by mrobinson** [comment]
@tharkum Are you still seeing this problem after #40459?

**Comment by tharkum** [comment]
@mrobinson < The following test haven't test output page so I cannot check this issue properly without `Rerun` buttom
` ./mach test-wpt tests/wpt/tests/html/canvas/element/manual/wide-gamut-canvas/canvas-display-p3-drawImage.https.html -r
`
