### ISSUE TITLE
Dark themes are not applied properly on startup

### ISSUE THREAD

**Issue by burhankhanzada** [servo/servo#40437]
**Describe the bug:**
There is still issue that if system theme is dark the with intial load of website always load with light mode.

**To Reproduce:**
just run servoshell

**Platform:**
Tested on MacOS

**Comment by jdm** [comment]
This should have been fixed with #40395.

**Comment by burhankhanzada** [comment]
> This should have been fixed with [#40395](https://github.com/servo/servo/issues/40395).

Yeah it should but its not, I just tested with latest pull on main branch then run servoshell and its not fixed.

**Comment by yezhizhen** [comment]
cc @mrobinson Now it still always light theme in first time, but works after refresh.

**Comment by burhankhanzada** [comment]
Also #40268 still happening.

**Comment by mrobinson** [comment]
Here's what I had to do to reproduce this issue for future reference:

1. Switch the system theme to a dark theme.
2. Start servoshell (the servoshell page doesn't have a CSS theme, so this step itself isn't sufficient).
3. Open a new tab and observe that the new tab page was using the light theme.
