### ISSUE TITLE
Resizing the window is causing style recalc to occur (incremental layout totally broken)

### ISSUE THREAD

**Issue by pcwalton** [servo/servo#5227]
We really need tests for this stuff.

**Comment by cojennin** [comment]
Do you have some suggestions for how to model/implement these tests? I'd like to take a shot at writing a few.

**Comment by pcwalton** [comment]
This is fixed now.

**Comment by jdm** [comment]
@pcwalton To be clear, we still don't have tests for this, right?

**Comment by pcwalton** [comment]
Right, we don't. (Neither does Gecko, from talking to @bzbarsky in Portland -- testing to make sure you didn't reflow *too much* is a tough problem.)

**Comment by bzbarsky** [comment]
Though note that dbaron is considering adding some sort of reflow or restyle counters to make that sort of thing testable.
