### ISSUE TITLE
Incremental layout removes line breaks

### ISSUE THREAD

**Issue by narfg** [servo/servo#5711]
Consider the following test case:
```html
<!DOCTYPE html>
<html>
<head>
<title>Line break</title>
<!-- Incremental layout line breaks. -->
<style>
@font-face {
    font-family: 'ahem';
    src: url(fonts/ahem/ahem.ttf);
}
body {
    font-family: Ahem;
    font-size: 12px;
}
</style>
</head>
<body>
<div style="width: 500px; background-color: #3F3FFF;">
X<br>X<br>X
</div>
<div style="width: 500px; background-color: #00FF00;">
X<br>X<br>X
</div>
</body>
</html>
```
If I hover the mouse cursor above the blue div, the line breaks in the green div are removed and vice versa.
This doesn't happen with the option -i.
Original state:
![1](https://cloud.githubusercontent.com/assets/158917/7180346/24029498-e441-11e4-83c5-76ce663b6e3d.png)
Mouse cursor in one of the divs:
![2](https://cloud.githubusercontent.com/assets/158917/7180345/2401430e-e441-11e4-9f07-5eb84829db12.png)
![3](https://cloud.githubusercontent.com/assets/158917/7180347/2406e76e-e441-11e4-905a-77dfd5108f1d.png)

**Comment by jdm** [comment]
cc @pcwalton

**Comment by mbrubeck** [comment]
I can't reproduce this on Servo master.  This was probably fixed by #5493.

**Comment by jdm** [comment]
`<narfg> mbrubeck: I can still reproduce the issue I described in #5711 on master.`

**Comment by narfg** [comment]
This was fixed by #5816.
