### ISSUE TITLE
./mach test-tidy --faster shouldn't display anything when the file list is empty

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#9778]
```
keith$ ./mach test-tidy --faster
Checking files for tidiness...
  Progress: 100% (17/17)
Running the WPT lint...

tidy reported no errors.
```

**Comment by jdm** [comment]
Code: `python/tidy.py`

**Comment by Ms2ger** [comment]
Why?

**Comment by KiChjang** [comment]
Because it is not run at all when using the --faster option.

**Comment by Wafflespeanut** [comment]
Damn, I forgot that! On the brighter side, it's a good first issue :)

**Comment by Ms2ger** [comment]
That was fixed in #9394

**Comment by KiChjang** [comment]
I just did a git pull from master and I still see the following:
```
keith$ ./mach test-tidy --faster
Checking files for tidiness...

Running the WPT lint...

tidy reported no errors.
```

**Comment by jdm** [comment]
@Ms2ger means that the WPT lint was made to run when --faster is used in #9394, so the message is actually correct.

**Comment by Wafflespeanut** [comment]
@Ms2ger If there are no changes to the WPT files in the diff, then no files are generated, and so the lint doesn't run.

**Comment by KiChjang** [comment]
In which case, we should instead change the --help message, it says the following for me:
```
keith$ ./mach test-tidy --help
usage: mach [global arguments] test-tidy [command arguments]

Run the source code tidiness check

Global Arguments:
  -v, --verbose         Print verbose output.
  -l FILENAME, --log-file FILENAME
                        Filename to write log data to.
  --log-interval        Prefix log line with interval from last message rather
                        than relative time. Note that this is NOT execution
                        time if there are parallel operations.
  --log-no-times        Do not prefix log lines with times. By default, mach
                        will prefix each output line with the time since
                        command start.
  -h, --help            Show this help message.
  --debug-command       Start a Python debugger when command is dispatched.

Command Arguments:
  --faster       Only check changed files and skip the WPT lint in tidy
  --no-progress  Don't show progress for tidy
```

**Comment by Wafflespeanut** [comment]
No, if there are changes to the WPT files in the diff, then tidy does pass it to the lint.

**Comment by Wafflespeanut** [comment]
Mmm, nope - a better title would be...

**Comment by zakorgy** [comment]
I would like to try this

**Comment by KiChjang** [comment]
Go for it!

**Comment by zakorgy** [comment]
I got a little confused, with the --faster should the tidy-test skip the WPT lint in tidy and display nothing if the file list is empty, or just skip the WPT lint in tidy as in the --help message?

**Comment by Wafflespeanut** [comment]
@zakorgy the former - don't display the messages when the file list is empty. For example, if the WPT lint gets an empty list, then we shouldn't show "Checking WPT..." message

**Comment by jdm** [comment]
This should be fixed by #10074.
